# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: bicep

on:  
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3
    - name: 'Lint code'
      run: |
        az bicep build --file ./infra/storage.bicep     
        
