# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: bicep

on:  
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
env:
  AZURE_SUB_ID: '97a9a77c-8104-417e-995b-eace2cfd65eb'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3

    - name: 'Az login'
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDS}}

    - name: 'set sub'
      run: |
         az account set --subscription ${{env.AZURE_SUB_ID}}
    - name: 'Lint code'
      run: |
        az bicep build --file ./infra/storage.bicep     
        
    - name: 'Bicep validation'
      run: |
        az deployment sub validate \
            --location WEST_EUROPE \
            --template-file ./infra/storage.bicep