name: .NET Core CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
   

env:
  AZURE_WEBAPP_NAME: b1webapp    # set this to your application's namei
  AZURE_WEBAPP_PACKAGE_PATH: './published'       # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'           # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@main
      
    
      - name: 'Az login'
        uses: azure/login@v1
        with:
            creds: ${{secrets.AZURE_CREDS}}
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build 
        run: |
          dotnet restore
          dotnet build --configuration Release
        working-directory: sampleapp11

      # Run dotnet build and publish
      - name: dotnet  publish
        run: |
         
          dotnet publish --configuration release --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        working-directory: sampleapp11 

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v1
        with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        