# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: bicep

on:  
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
env:
  AZURE_SUB_ID: '97a9a77c-8104-417e-995b-eace2cfd65eb'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3

    - name: 'Az login'
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDS}}

    - name: 'set sub'
      run: |
         az account set --subscription ${{env.AZURE_SUB_ID}}
    - name: 'Lint code'
      run: |
        az bicep build --file ./infra/storage.bicep     
        
    - name: 'Bicep validation'
      run: |
        az deployment sub validate \
            --location westeurope \
            --template-file ./infra/main.bicep

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: sampleapp11

      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: sampleapp11
      
    - name: Test
      run: dotnet test
      working-directory: sampleapp11

    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: sampleapp22

      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: sampleapp22
      
    - name: Test
      run: dotnet test
      working-directory: sampleapp22

  deploy_on_dev:
    runs-on: ubuntu-latest
    needs: build
    environment: Dev
    steps:
     # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUB_ID }}
        scope: subscription
        template: ./main.bicep
        failOnStdErr: false
