name: MainRelease

on:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '45 2 * * *'
    - cron:  '45 3 * * *'
  workflow_dispatch:
   inputs:
      env:
        required: true
        type: string
        default: 'Dev'
         options:
          - Dev
          - Test
          - Prod

env:
 env_name: github.event.inputs.env 

jobs:
 call-devflow:
 steps:
   
  - name: On schedule set env var
        if: github.event.schedule == '45 2 * * *'
        run: echo "running on schedule for dev"
        env_name: Dev
   # runs-on: ubuntu-latest
  - name: Run Dev flow
    uses: Harshitha-Learn/learningrepo/.github/workflows/main (2).yml@main
    with:
      env: ${{env.env_name}}
    secrets: inherit
    
  call-testflow:
   # runs-on: ubuntu-latest
    if: github.event.schedule == '45 3 * * *'
    uses: Harshitha-Learn/learningrepo/.github/workflows/main (2).yml@main
    with:
      env: ${{env.env_name}}
    secrets: inherit
