name: Releasepipeline
on:
  #push:
   # branches: [ "main" ]
  workflow_dispatch:
   inputs:      
      env:
        type: environment
        description: Select the environment
        required: true
  workflow_call:
   inputs:      
      env:
        type: string
        description: Select the environment
        required: true
   

env:
  AZURE_WEBAPP_NAME: b1webapp 
  AZURE_WEBAPP_NAME_test: b2webapp  # set this to your application's namei
 # AZURE_WEBAPP_PACKAGE_PATH: './published'       # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'           # set this to the dot net version to use

jobs:
  #build:
  build:
    # runs-on: ubuntu-latest
    uses: ./.github/workflows/buildci.yml
   
    secrets: inherit
  
         
  deploy_on_dev:
     #  if: github.event.inputs.env == 'Dev' 
       if: ${{ github.event.inputs.env == 'Dev'  || inputs.env == 'Dev' }}
       runs-on: ubuntu-latest
       needs: build
       environment: Dev
       steps:
           # Checkout the repo
          - name: List var
            run: |
             echo $GITHUB_SHA
             echo $GITHUB_REPOSITORY
             echo $GITHUB_REF
    
          - name: 'Az login'
            uses: azure/login@v1
            with:
                creds: ${{secrets.AZURE_CREDS}}
          
          - uses: actions/download-artifact@v3
            with:
                name: webapp1
                path: ./sampleapp11/Dev_${{github.run_id}}/
          

          - name: 'Run Azure webapp deploy action '
            uses: azure/webapps-deploy@v2
            with: 
                  app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
                  package: ./sampleapp11/Dev_${{github.run_id}}/

          - name: Send custom JSON data to Slack workflow
            id: slack
            if: always()
            uses: slackapi/slack-github-action@v1.23.0
            with:
              # For posting a rich message using Block Kit
              payload: |
                        {
                         "blocks": [
                            {
                              "type": "section",
                              "text": {
                                "type": "mrkdwn",

                             "text": "CCM GitHub Action result: \n *Status:* ${{ job.status }}\n *Job Name:* ${{ github.job }}  \n *worflow:* ${{ github.workflow }} \n *Repository:* ${{ github.repository }} \n Link: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} "  }
                            }
                          ]
                        }
            env:
              SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
              SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  deploy_on_test:
       if: ${{ github.event.inputs.env == 'Test'  || inputs.env == 'Test' }}
      # if: github.event.inputs.env == 'Test' 
       runs-on: ubuntu-latest
       needs: build
       environment: Test
       steps:
           # Checkout the repo
          - name: List var
            run: |
             echo $GITHUB_SHA
             echo $GITHUB_REPOSITORY
             echo $GITHUB_REF
             echo ${{github.run_number}}
             
    
          - name: 'Az login'
            uses: azure/login@v1
            with:
                creds: ${{secrets.AZURE_CREDS}}
          
          - uses: actions/download-artifact@v3
            with:
                name: webapp1
                path: ./sampleapp12/
          

          - name: 'Run Azure webapp deploy action '
            uses: azure/webapps-deploy@v2
            with: 
                  app-name: ${{ env.AZURE_WEBAPP_NAME_test }} # Replace with your app name
                  package: ./sampleapp12/

          - name: Send custom JSON data to Slack workflow
            id: slack
            if: always()
            uses: slackapi/slack-github-action@v1.23.0
            with:
              # For posting a rich message using Block Kit
              payload: |
                        {
                         "blocks": [
                            {
                              "type": "section",
                              "text": {
                                "type": "mrkdwn",

                             "text": "CCM GitHub Action result: \n *Status:* ${{ job.status }}\n *Job Name:* ${{ github.job }}  \n *worflow:* ${{ github.workflow }} \n *Repository:* ${{ github.repository }} \n Link: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} "  }
                            }
                          ]
                        }
            env:
              SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
              SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
