name: test checkout

on:  
  workflow_dispatch:
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3
    
    - name: scirpt pwsh
      shell: pwsh
      run: |
             Get-ChildItem -Path ./
               
    - name: List var
      run: |
         echo $GITHUB_SHA
         echo $GITHUB_REPOSITORY
         ls test.txt
