name: .NET Core CI seperate

on:
  
  workflow_dispatch:
    
   

env:
  AZURE_WEBAPP_NAME: b1webapp    # set this to your application's namei
 # AZURE_WEBAPP_PACKAGE_PATH: './published'       # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'           # set this to the dot net version to use

jobs:
 
  
  deploy_on_dev:
       runs-on: ubuntu-latest
      # needs: build
       environment: Dev
       steps:
           # Checkout the repo
         
    
          - name: 'Az login'
            uses: azure/login@v1
            with:
                creds: ${{secrets.AZURE_CREDS}}
          
          - uses: actions/download-artifact@v3
            with:
                name: webapp1
                path: ./sampleapp11/
          

          - name: 'Run Azure webapp deploy action '
            uses: azure/webapps-deploy@v2
            with: 
                  app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
                  package: ./sampleapp11/
