
name:  testscirptflow

on:  
  workflow_call:
   inputs:      
      Environment:
        type: string
        description: Environment name for Release

env: 
 LOCATION: 'westeurope'

jobs:
  Build:
    uses: ./.github/workflows/buildci.yml 
    secrets: inherit
  
 # if: ${{ github.event.inputs.env == 'Dev'  || inputs.env == 'Dev' }}
  Dev_Deploy:
     #  if: github.event.inputs.env == 'Dev' 
       if: ${{ github.event.inputs.env == 'Dev' }}
       runs-on: ubuntu-latest
       needs: Build
       environment: Dev
       steps:
           # Checkout the repo
          - uses: actions/checkout@v3
 
          - name: List var
            run: |
             echo $GITHUB_SHA
             echo $GITHUB_REPOSITORY
             echo $GITHUB_REF
             
  Test_Deploy:
     #  if: github.event.inputs.env == 'Dev' 
       if: ${{ github.event.inputs.env == 'Test' }}
       runs-on: ubuntu-latest
       needs: Build
       environment: Dev
       steps:
           # Checkout the repo
          - uses: actions/checkout@v3
 
          - name: List var
            run: |
             echo $GITHUB_SHA
             echo $GITHUB_REPOSITORY
             echo $GITHUB_REF
             
             
  Prod_Deploy:
     #  if: github.event.inputs.env == 'Dev' 
       if: ${{ github.event.inputs.env == 'Prod' }}
       runs-on: ubuntu-latest
       needs: Build
       environment: Prod
       steps:
           # Checkout the repo
          - uses: actions/checkout@v3
 
          - name: List var
            run: |
             echo $GITHUB_SHA
             echo $GITHUB_REPOSITORY
             echo $GITHUB_REF
    
        
