name: Schedule Test deploy 

on:

#  schedule:
    # * is a special character in YAML so you have to quote this string
  #  - cron:  '37 14 * * *'
  workflow_dispatch:
 #  inputs:
  #    env:
  #      required: true
  #      type: string
  #      default: 'Dev'

permissions: write-all

env: 
 ref-branch: 'main' #change this to release branch name
 workflow_name: Releasepipeline.yml


jobs:
 workflowcall-api-trigger:
    runs-on: ubuntu-latest
    steps:
        - name: REST API with curl
          run: | 
              response =  $(curl -X POST "https://api.github.com/repos/Harshitha-Learn/learningrepo/actions/workflows/${{ env.workflow_name }}/dispatches" -H "Accept: application/vnd.github+json" -H "Authorization: token ${{secrets.Token_pat}} " -H "X-GitHub-Api-Version: 2022-11-28" -d '{"ref": "${{ env.ref-branch }}","inputs":{"env":"Dev"}}')
              echo "response from curl= $response"
            
   # runs-on: ubuntu-latest
  #  uses: Harshitha-Learn/learningrepo/.github/workflows/Releasepipeline.yml@releases-2.0
   # with:
  #    env: Test
  #  secrets: inherit
   
  
   
