name: Schedule Test deploy 

on:

#  schedule:
    # * is a special character in YAML so you have to quote this string
  #  - cron:  '37 14 * * *'
  workflow_dispatch:
 #  inputs:
  #    env:
  #      required: true
  #      type: string
  #      default: 'Dev'

permissions: write-all
env:
 Environment: Dev

jobs:
 workflowcall-api-trigger:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: | 
        curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \ 
          -H "Authorization: token ${{secrets.Token_pat}}" \
          -d '{"ref": "main","inputs":{"env":"Dev"}}' \
          https://api.github.com/repos/Harshitha-Learn/learningrepo/actions/workflows/Releasepipeline/dispatches
# call-cicdflow:
   # runs-on: ubuntu-latest
  #  uses: Harshitha-Learn/learningrepo/.github/workflows/Releasepipeline.yml@releases-2.0
   # with:
  #    env: Test
  #  secrets: inherit
   
  
   
