name: Schedule Dev deploy nightly

on:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 2 * * *'
  workflow_dispatch:
   inputs:
     environment:
        type: environment
        description: Select the environment

jobs:
 call-cicdflow:
   # runs-on: ubuntu-latest
    uses: Harshitha-Learn/learningrepo/.github/workflows/main (2).yml@main
    with:
      env: ${{ inputs.environment }}
    secrets: inherit
   
  
   
